### 헬스 체크 (서버 상태 확인)
GET http://localhost:8081/users/health
Accept: text/plain

### 회원가입 요청 테스트
POST http://localhost:8081/users/signup
Content-Type: application/json

{
  "username": "jinju47373737",
  "password": "Test@1234",
  "address": "Seoul",
  "role": "CUSTOMER"
}


### 회원가입 요청 테스트
POST http://localhost:8081/users/signup
Content-Type: application/json

{
"username": "jinju1111737",
"password": "Test@1234",
"address": "Seoul",
"role": "MANAGER"
}

### 로그인 요청 테스트
POST http://localhost:8081/users/login
Content-Type: application/json

{
  "username": "jinju1111737",
  "password": "Test@1234"
}

### 회원가입 요청 테스트
POST http://localhost:8081/users/signup
Content-Type: application/json

{
  "username": "jinjukim2312",
  "password": "Test@1234",
  "address": "경기도 수원시 장안구 만석로159번길31",
  "role": "CUSTOMER"
}

### 회원가입 요청 테스트
POST http://localhost:8081/users/signup
Content-Type: application/json

{
  "username": "jinjukim2312",
  "password": "Test@1234",
  "address": "경기도 수원시 장안구 경수대로1031번길",
  "role": "MANAGER"
}


### 회원가입 요청 테스트
POST http://localhost:8081/users/signup
Content-Type: application/json

{
  "username": "lionking2312",
  "password": "Test@1234",
  "address": "경기도 수원시 장안구 파장로110번길",
  "role": "CUSTOMER"
}

### 회원가입 요청 테스트
POST http://localhost:8081/users/signup
Content-Type: application/json

{
  "username": "merong4473",
  "password": "Test@1234",
  "address": "경기도 수원시 장안구 만석로159번길31 104동 1403호",
  "role": "CUSTOMER"
}

### 로그인 요청 테스트 (토큰 받기)
POST http://localhost:8081/users/login
Content-Type: application/json

{
  "username": "merong4473",
  "password": "Test@1234"
}


### 회원가입 요청 테스트
POST http://localhost:8081/users/signup
Content-Type: application/json

{
  "username": "iamManager44",
  "password": "Test@1234",
  "address": "경기도 수원시 장안구 만석로159번길31 104동 1403호",
  "role": "MANAGER"
}


### 로그인 요청 테스트 (토큰 받기)
POST http://localhost:8081/users/login
Content-Type: application/json

{
  "username": "master1",
  "password": "Master@1234"
}

> {%
    // 응답 받은 JSON에서 accessToken을 추출하여 'auth_token' 변수에 저장
    client.global.set("auth_token", response.body.accessToken);
%}

### 유저 권한 변경
PUT http://localhost:8081/admin/role/update/jinju1111737
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "role": "CUSTOMER"
}

