### 1. MASTER 회원가입
# 먼저 'manager-test'라는 ID로 MANAGER 계정을 생성합니다.
POST http://localhost:8081/users/signup
Content-Type: application/json

{
  "username": "master1",
  "password": "Master@1234",
  "address": "서울특별시 강남구 테헤란로 212",
  "role": "MASTER"
}

### 2. MANAGER 로그인 (토큰 획득)
# 위에서 가입한 ID로 로그인하여 JWT 토큰을 발급받습니다.
# 이 요청이 성공하면 'auth_token'이라는 변수에 토큰이 저장됩니다.
POST http://localhost:8081/users/login
Content-Type: application/json

{
  "username": "managertest4473",
  "password": "Manager@1234"
}

> {%
    // 응답 받은 JSON에서 accessToken을 추출하여 'auth_token' 변수에 저장
    client.global.set("auth_token", response.body.accessToken);
%}

### 3. 카테고리 생성 (MANAGER 권한 필요)
# 2번에서 저장한 'auth_token'을 Authorization 헤더에 담아 보냅니다.
# @PreAuthorize("hasRole('MANAGER')") 설정을 테스트합니다.
POST http://localhost:8083/categories
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "category_name": "중식"
}

### 4. 카테고리 목록 조회 (테스트용)
# 3번에서 생성한 "치킨" 카테고리가 잘 들어갔는지 확인합니다.
# 이 API는 토큰이 필요 없습니다. (CategoryController 설정에 따름)
GET http://localhost:8083/categories
Accept: application/json
Authorization: Bearer {{auth_token}}

### 5. 가게 목록 조회 (테스트용)
GET http://localhost:8083/stores
Accept: application/json
Authorization: Bearer {{auth_token}}

### 6. 가게 상세 조회 (테스트용)
GET http://localhost:8083/stores/b989eec9-4dbe-4f50-ac48-bd33353cfe40
Accept: application/json
Authorization: Bearer {{auth_token}}

### 7. 가게 등록 (테스트용)
POST http://localhost:8083/stores/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "store_name": "우렬이네",
  "owner_id": "asfdasdㅁㅁㅁㅁ",
  "store_address": "서울 강남구 역삼동 646-15",
  "description": "아주 맛있는 치킨집",
  "store_rating_avg": 0,
  "store_review_count": 0
}

### 8. 가게 수정(테스트용)
PUT http://localhost:8083/stores/update/6ef796ee-28cd-4284-98bc-860ba26df4bc
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "description": "맛있는 치킨"
}